### ISSUE TITLE
COMMENT:  good work

### ISSUE THREAD

**Issue by ghost** [AaronLiddiment/RGBLEDS#1]
Hi thank you for these classes! I'll give them a try soon. I just finished the hardware part of my rgb led display and can't wait to try out your code. Will it be possible to display text that is higher then 7 pixels?  

watch the first test of my ledscreen:
https://www.youtube.com/watch?v=EEqzSQTmnw0

Best regards,
Kasper

**Comment by ghost** [comment]
Also it would be very welcome if you could place comments in your code so its much easier to see what's going on.

**Comment by AaronLiddiment** [comment]
Hi,
Thank you :)
It's always good to know your work is used. The text width is currently limited to 8 pixels, but the height has no such limit. The FontRobotron.h is a good example of the easiest way to define a font in source code using the binary macro.
Sometimes I comment my code but often when I am in the 'zone' I find it just spaces the code out too much so that I have to use too many page up/downs to get around ;)
At least I managed to write some instructions and examples that use most features.
I must get around to writing the instructions for the Matrix & Sprite classes. The Matrix class was really hard to write as I wanted to make it fast & small but still allow for different matrix wiring arrangements. It was the first piece of templated code that I have written and is fairly unique amoungst led matrix code for its flexibility.

I like the look of you matrix, in particular the defined squares. I did come across someone doing that by making their own diffusers with a 3D printer. Unfortunately I am broke at the moment and a 3D printer is just a dream.....
How did you make yours?
Best regards
Aaron Liddiment

**Comment by terrag42** [comment]
Hello Aaron,
I recently received a Kickstarter reward from Garrett (hey, that's my name too!) at Macetech.com
It's a pair of RGB LED sunglasses (shades) that use WS2812B pixels. Garrett's code for his shades uses the FastLed library as well. I was hoping to use your code with my shades, but my matrix layout has gaps in it to allow for the curved edges and the gap for your nose. Garrett has [his code on GitHub](https://github.com/macetech/RGBShades), and he wrote a header file called "XY" that takes care of this problem when using x,y coordinates, but I am having trouble incorporating it into your code, as I keep getting errors. Do you know of a good way to use your code on a matrix that has "gaps" in it?
Thank you!
-Garrett
