### ISSUE TITLE
Hex values? Cleaner configuration options? A few critiques.

### ISSUE THREAD

**Issue by webdevbrian** [AaronLiddiment/RGBLEDS#5]
Hi,

Thanks for the library, few questions and critiques : 
- Is there any way we can get standard hex colors integrated with this?
- Is there any way we can simplify specifying text? For instance, right now to define a line of text I'm setting it up in three separate places. One above the setup creating the text config array with text, second the parameters in the setup, and in the loop. Wish there was a way to define this twice, once in the setup, once in the loop, with a lot more easy to understand settings.
- Effects are awesome, the configurability of this is abysmal at best in my opinion. "'xNN" is not the way to define settings, let along in a single line with ambiguous text sitting in the middle with no assigned configuration parameter, e.g."text" "text here". It's all over the place.

I think if this was cleaned up a bit this would be a hell of a library, in it's current state, it's almost impossible to use this on anything less than an arduino mega due to the shear size of the settings you need to define for each bit of text. I can get past the size of the libraries, but the settings for defining text, maintainability, really puts me off about this lib.

Thanks

**Comment by AaronLiddiment** [comment]
Hi,
There is nothing stopping you declaring #defines using RGB for the colours:

#define PURPLE EFFECT_RGB "\xff\x00\xff"
#define YELLOW EFFECT_RGB "\xff\xff\x00"
const unsigned char TxtDemo[] = { PURPLE "This is Purple text"
                                                        YELLOW "and this is Yellow text" };

The method I have used for specifying the wide range of options is the most memory efficient method. Do you realise that each \xNN is converted by the compiler into a single byte!
There are readable #defines for all the options with only the parameters needing to be specified as numbers!

Your text array declaration is not limited to a single line! See the examples provided with the library. Also note that if you have followed the examples and declared the array as 'const unsigned char' outside of any function that it will be placed in ROM taking up program space and not in the more limited RAM space.
If you require text messages with changing elements then there are various ways of doing this efficiently but without seeing your specific code I cannot advise you.

I cannot understand why you are having to setup text in 3 separate places, I can only assume your programming knowledge is limited and as for "sheer size of the settings" I am puzzled!
Please post/send me a copy of your code so that I can advise you better.

Regards
Aaron
