### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by alexandercheyns** [AaronLiddiment/RGBLEDS#7]
Hello thanks for the code but I can't seem to get it working ? Very new to fastled and just trying to understand everything
![schermafbeelding 2015-10-02 om 11 10 12](https://cloud.githubusercontent.com/assets/14938362/10243066/35755ff0-68f6-11e5-9910-559a806f677a.png)

**Comment by AaronLiddiment** [comment]
Hi, thanks, 
I think your issue is that you need to move the 3 folders in RGBLEDS out into the Libraries folder.
I didn't realise that when I made the GitHub it would place the 3 folders in one called RGBLEDS in the zip file, you are not alone though, many people have had this same issue. I must get around to either finding a way to change it or at least posting a warning on the main page !

**Comment by alexandercheyns** [comment]
Hi,

thanks for the quick reply, I figured it had to be something with faulty
libraries and i moved them around a couple of times but not in the way you
said so its up and working now. Thanks again for the code !

2015-10-02 13:16 GMT+02:00 AaronLiddiment notifications@github.com:

> Hi, thanks,
> I think your issue is that you need to move the 3 folders in RGBLEDS out
> into the Libraries folder.
> I didn't realise that when I made the GitHub it would place the 3 folders
> in one called RGBLEDS in the zip file, you are not alone though, many
> people have had this same issue. I must get around to either finding a way
> to change it or at least posting a warning on the main page !
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AaronLiddiment/RGBLEDS/issues/7#issuecomment-144992821
> .

## 

---

Alexander Cheyns
Industrial designer  view latest projects
http://facebook.com/designadayconcepts //
homepage // http://ac-id.be //

founder\* designaday.be http://designaday.be\* // daily product and concept
design //
Kortrijk, Belgium

---
